sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "12.0"
branches:
  only:
    - main
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - ng build --prod
deploy:
  skip_cleanup: true
  provider: firebase
  on:
    branch:
    - main
  token: 
    secure: FIREBASE_TOKEN
  message: "this is an automatic deployment by travis - CI as a result of pushing to main"